version: "3.9"
services:

   db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: bazaar
       POSTGRES_DB: bazaar
     ports:
       - 5436:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data